services:
  - type: worker
    name: rspamd-telegram-bot
    env: docker
    dockerfilePath: ./docker/Dockerfile
    envVars:
      - key: TELOXIDE_TOKEN
        sync: false  # Set this manually in Render dashboard 