# .github/workflows/integration-tests.yml
on:
  push:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Redis and Rspamd
        run: |
          sudo apt-get update && sudo apt-get install -y lsb-release wget gpg ca-certificates redis-server
          CODENAME=$(lsb_release -c -s)
          sudo mkdir -p /etc/apt/keyrings
          wget -O- https://rspamd.com/apt-stable/gpg.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/rspamd.gpg > /dev/null
          echo "deb [signed-by=/etc/apt/keyrings/rspamd.gpg] http://rspamd.com/apt-stable/ $CODENAME main" \
            | sudo tee /etc/apt/sources.list.d/rspamd.list
          sudo apt-get update && sudo apt-get install -y rspamd

      - name: Configure Rspamd
        run: |
          sudo mkdir -p /etc/rspamd/lua.local.d
          sudo cp -R rspamd-config/lua.local.d/. /etc/rspamd/lua.local.d/
          sudo rspamadm configtest

      - name: Start services
        run: |
          sudo service redis-server start
          sudo service rspamd restart
          for i in {1..10}; do
            if redis-cli ping | grep -q PONG && rspamadm configtest > /dev/null; then
              echo "Services are up."
              break
            fi
            echo "Waiting for Redis & Rspamd... ($i)"
            sleep 1
          done

      - name: Build project
        run: cargo build --verbose

      - name: Run integration tests
        run: cargo test -- --test-threads=1
